apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "base-app.fullname" . }}
  labels:
    {{ include "base-app.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{ include "base-app.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{ include "base-app.labels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ include "base-app.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
