apiVersion: v1
kind: Service
metadata:
  name: {{ include "base-app.fullname" . }}
  labels:
    {{ include "base-app.labels" . | nindent 4 }}
spec:
  selector:
    {{ include "base-app.selectorLabels" . | nindent 4 }}
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
